config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :registered_applications, only: [:show, :create, :new, :edit, :update, :destroy], as: :applications
  end

  resources :registered_applications, only: [] do
    resources :events, only: [:create, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  authenticated :user do
    root :to => 'registered_applications#index', as: :authenticated_root
  end

  root 'welcome#index'
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :events
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :application
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
         
  has_many :applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_filter :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_access_control_headers

  def preflight
    head 200
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = Application.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.nil?
      return render json: "unregistered application", status: :unprocessable_entity
    end

    event = registered_application.events.new(event_params)

      if event.save
        render json: event, status: :created
      else
        render json: { errors: event.errors }, status: :unprocessable_entity
      end
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @applications = current_user.applications.where(user_id: current_user.id)
  end

  def show
    @application = current_user.applications.find_by(title: params[:id])
    @events_group = @application.events.group_by(&:name)
  end

  def new
    @application = current_user.applications.new
  end

  def create
    @application = current_user.applications.new(application_params)

    if @application.save
      flash[:notice] = "You added an application into your list."
      redirect_to root_path
    else
      flash[:alert] = @applications.errors.full_messages
      render root_path
    end
  end

  def edit
    @application = current_user.applications.find_by(title: params[:id])
  end

  def update
    @application = current_user.applications.find_by(title: params[:id])
    old_title = @application.title
    same_name = current_user.applications.where(title: params[:application][:title])

    if same_name.length > 0 && old_title != params[:application][:title]
      flash[:notice] = "You need to chage your application's name. Someone already use that name."
      redirect_to user_application_path(current_user, application)
    else
      @application.assign_attributes(application_params)
      @application.assign_attributes(slug: params[:title])

      if @application.save
        flash[:notice] = "Your change has been saved."
        redirect_to root_path
      else
        flash[:alert] = @applications.errors.full_messages
        render root_path
      end
    end
  end

  def destroy
    application = Application.find_by(title: params[:id])

    if current_user.id != application.user_id
      flash[:alert] = "You can't delete other person's application."
      redirect_to root_path
    else
      if application.destroy
        flash[:notice] = "Your application has been deleted."
        redirect_to root_path
      else
        flash[:alert] = applications.errors.full_messages
      end
    end
  end

  private

  def application_params
    params.require(:application).permit(:title, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.6/highcharts.js" %>
    <%= javascript_include_tag "https://raw.githubusercontent.com/ankane/chartkick/master/app/assets/javascripts/chartkick.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <div class='head_row'>
        <%= link_to  image_tag( 'http://bsccongress.com/wp-content/uploads/2016/06/white-letter-b-clip-art.png', class: 'logo_sign'), root_path%>
        <nav>
          <% if current_user %>
              <%= link_to 'Edit account', edit_user_registration_path, class: 'btn btn-default' %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
          <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-default' %>
              <%= link_to "sign in", user_session_path, class: 'btn btn-default' %>
          <% end %>
        </nav>
      </div>
      <% if notice %>
        <div class='bg-info'>
          <%= notice %>
        </div>
      <% elsif alert %>
        <div class='bg-danger'>
          <%= alert %>
        </div>
      <% end %>
      
      <div class='row'>
        <%= yield %>
      </div>
    </div>
    </body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for [current_user, @application] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  
  <%= f.submit "Save" %>
<% end %>

app/views/registered_applications/edit.html.erb
<div class='app_edit_page'>
  <h2><%= @application.title %>'s edit page</h2>
  <%= render 'form' %>
</div>

app/views/registered_applications/index.html.erb
<div class='app_index_page'>
  <div class=col-md-12'>
    <h1><%= current_user.email %> 's applications list</h1>
  </div>
  <div class=col-md-12'>
    <%= link_to 'Register New Application', new_user_application_path(current_user), class: 'btn btn-primary register_new_app' %>
  </div>
  <div class='row'>
    <% @applications.each_with_index do |app, index| %>
      <div class='col-md-12 app_list'>
        <div class='row'>
          <div class='col-md-4 app_list_id'>
            <%= index + 1 %>
          </div>
          <div class='col-md-4 app_list_titel'>
            <%= link_to app.title, user_application_path(current_user, app) %>
          </div>
          <div class='col-md-4'>
            <%= link_to 'Delete', user_application_path(current_user, app), method: :delete, class: 'btn btn-danger register_delete_app' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class='app_new_view'>
  <h2>Register your application</h2>

  <%= render 'form' %>
</div>

app/views/registered_applications/show.html.erb
<div class='app_show_view'>
  <h2><%= @application.title %></h2>
  </br>
  <h3>URL: <%= @application.url %></h3>
  <div class='col-md-12'>
    <% @events_group.each do |event| %>
      <p>Name: <span class='event_name'><%= event[0] %></span>, Count: <span class='event_count'><%= event[1].count %></span></p>
    <% end %> 
    <div class='row' >
      <div class='col-md-12' >
        <%= pie_chart @application.events.group(:name).count, class: 'graph' %>
        <%= line_chart @application.events.group('date("events"."created_at","start of day")').count %>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_user_application_path(current_user, @application), class: 'btn btn-info register_edit_app' %>
</div>

app/views/welcome/index.html.erb
<div class='welcome_view'>
  <% if current_user %>
    <h1>Welcome</h1>
    <h2> <%= current_user.email %> </h2>
  <% else %>
    <h1>Welcome to Yen Metrics</h1>
  <% end %>
</div>